travis:
  secure:
    BINSTAR_TOKEN: Fm/jm8rqCn7TuLVreaMAL+jCLOt00JShVlKnK9OdMcKP0rS+drl5vI5cECfmlJrsJU8gGGQe1u6dUu/k/HSD0WLjMhIow9xMjlZNkmWuGZSL5fRJQdc/tqWaNgs37ONTvrWEbrSb25JmdXReDlroWPAsdvd6N4Av0KS7i8vrZ3qhO3T2vrGddLg7lzimR1iw+zkHeq/wigxyInf8ugfk/nkBzDEBB2JKWSd8PeiLgbovoQUnX65EcYmH5Ywr8FdfC97+1QqE2SmTB0IYbqyTxNrm2MdngwuTjWWp3vgO2x9OoPGTV/dHT4Ra1dh6Lg0YY/MvxRsAsriz1gGoE4xBa1PwZSo0nDoFqSWKvWiA2V1Hn/QvEsxxGzSuB+RaXG0pRRLMOVUb2kwZ1w8eorW89uF9sYT7q2DqKi/RZwytEduJhWqh6Z4VdEPWVE/h8xuHA23+K7VtnJTF9SgFWmrHAQ/WIvrW6yXj3CrzG1fonFfR2z5J63bMol6/Y6DE1K6f0R5ye+jUOHvJn6thOFRa4OfBBrTwndOJbK9Fy5oa6QqzNkvO6OUgi1c2F3TRa+imDFtqjQG6brWrITkCQ+JM/svWGI2HPO56iRpvpDEr+HSIqJrr3aI0UrGwjk9ovKReJEgi55OHAf7vyL1GRNZ/C1ydVM4e52YGNZUMrneYSbc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
